name: Debug docker

on:
  push:
    paths:
      - '**'

jobs:
  docker_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v14

      - name: Setup devnet
        run: |
          mkdir devnet
          cd devnet
          nix-shell ../ -A matic-cli-shell --run "matic-cli setup devnet"

      - name: Run ganache
        run: |
          cd devnet
          nix-shell ../ -A matic-cli-shell --run "bash docker-ganache-start.sh" &

      - name: Run Heimdall
        run: |
          cd devnet
          nix-shell ../ -A matic-cli-shell --run "bash docker-heimdall-start-all.sh" &

      - name: Setup Bor
        run: |
          cd devnet
          nix-shell ../ -A matic-cli-shell --run "bash docker-bor-setup.sh" &

      - name: Run Bor
        run: |
          cd devnet
          nix-shell ../ -A matic-cli-shell --run "bash docker-bor-start-all.sh" &
