name: Debug docker

on:
  push:
    paths:
      - '**'

jobs:
  docker_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker version
        run: docker --version
